---
version: 1.0.1
stack: attxproject/attx
services:

  mysql:
    image: attxproject/unified-views-mariadb:stable-1.2
    stateful: true
    environment:
      MYSQL_ROOT_PASSWORD: "UV"
      MYSQL_PASSWORD: "UV"
    affinity:
      - label==master

  shared:
    image: attxproject/unified-views-shared:stable-1.2
    stateful: true
    environment:
      UV_DATABASE_SQL_PASSWORD: "UV"
    volumes:
      - uv-shared:/unified-views
    depends_on:
      - mysql
    affinity:
      - label==master

  backend:
    image: attxproject/unified-views-backend:stable-1.2
    environment:
      MUSER: "user"
      MPASS: "password"
    volumes:
      - uv-shared:/unified-views
      - sb-shared:/attx-sb-shared
    depends_on:
      - shared
      - mysql
      - mysql
    affinity:
      - label==master

  frontend:
    image: attxproject/unified-views-frontend:stable-1.2
    links:
      - ingress-lb/lb
    environment:
      - KONTENA_LB_INTERNAL_PORT=8080
      - KONTENA_LB_VIRTUAL_HOSTS=vm1190.kaj.pouta.csc.fi
    volumes:
      - uv-shared:/unified-views
      - sb-shared:/attx-sb-shared
    depends_on:
      - shared
      - mysql
      - backend
    affinity:
      - label==master

  attxdpus:
   image: attxproject/uv-attx-dpus:dev
# see your demo grid for this address
   environment:
     FRONTEND: "frontend-1.attx.demo-grid.kontena.local"
   depends_on:
     - mysql
     - backend
     - frontend
   affinity:
     - label==master

  uvprov:
    image: attxproject/uv-prov:dev
    environment:
      MHOST: "messagebroker"
    depends_on:
      - mysql

  es5:
    image: attxproject/attx-es5:dev
    links:
      - ingress-lb/lb
    environment:
#      KONTENA_LB_CUSTOM_SETTINGS: |
#        reqiallow ^GET\s.*\/_search\?*.*HTTP\/1\.1$
#        reqiallow ^POST\s.*\/_search\?*.*HTTP\/1\.1$
#        reqideny ^.*HTTP\/1\.1$
      KONTENA_LB_INTERNAL_PORT: 9210
      KONTENA_LB_VIRTUAL_HOSTS: vm1136.kaj.pouta.csc.fi
      KONTENA_LB_VIRTUAL_PATH: /elasticsearch

  fuseki:
    image: attxproject/attx-fuseki:dev
    ports:
      - "3030:3030"
    stateful: true
    environment:
      ADMIN_PASSWORD: "pw123"

  graphmanager:
    image: attxproject/gm-api:dev
    stateful: true
    environment:
      MHOST: "messagebroker"
      GHOST: "fuseki"
    volumes:
      - sb-shared:/attx-sb-shared
    depends_on:
      - fuseki
      - messagebroker
    affinity:
      - label==broker

  messagebroker:
    image: rabbitmq:3.6.12-management
    stateful: true
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASSWORD: "password"

  ldframe:
    image: attxproject/ldframe-service:dev
    stateful: true
    depends_on:
      - messagebroker
    environment:
      MHOST: "messagebroker"
      GMHOST: "graphmanager"
    volumes:
      - sb-shared:/attx-sb-shared
    affinity:
      - label==broker

  rmlservice:
    image: attxproject/rml-service:dev
    stateful: true
    environment:
      MHOST: "amqp://messagebroker"
      MUSER: "user"
      MPASS: "password"
      MEXCHANGE: ""
      MQUEUE: "rmlservice"
    volumes:
      - sb-shared:/attx-sb-shared
    depends_on:
      - messagebroker
    affinity:
      - label==broker

  provservice:
    image: attxproject/provenance-service:dev
    depends_on:
        - messagebroker
        - fuseki
    environment:
        MHOST: "messagebroker"
        GHOST: "fuseki"

  indexservice:
    image: attxproject/index-service:dev
    depends_on:
      - messagebroker
    environment:
      MHOST: "messagebroker"
      ESHOST: "es5"
    volumes:
      - sb-shared:/attx-sb-shared
    affinity:
      - label==broker

  testdata:
    image: attxproject/testdata:dev



volumes:
  uv-shared:
    external:
      name: ${STACK}-uv-shared
  sb-shared:
    external:
      name: ${STACK}-sb-shared
