version: '2'
services:

  mysql:
    image: attxproject/unified-views-mariadb:stable-1.2
    volumes:
      - ./uv-data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamroot!

  shared:
    image: attxproject/unified-views-shared:stable-1.2

  backend:
    image: attxproject/unified-views-backend:stable-1.2
    links:
      - mysql:mysql
    volumes_from:
      - mysql
      - shared

  frontend:
    image: attxproject/unified-views-frontend:stable-1.2
    volumes_from:
      - backend
      - shared
    ports:
      - 8080:8080
    depends_on:
      - shared
      - mysql

  attx-dpus:
    image: attxproject/uv-attx-dpus:stable-1.2
    depends_on:
      - mysql
      - backend

  uprov:
    image: attxproject/uv-prov:1.0
    ports:
      - 4301:4301
    depends_on:
      - mysql

  essiren:
    image: attxproject/essiren:1.0
    volumes:
      - ./attx-data/essiren:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300

  es5:
    image: attxproject/attx-es5:1.0
    volumes:
      - ./attx-data/elasticsearch5:/usr/share/elasticsearch/data
    ports:
      - 9210:9210
      - 9310:9310

  fuseki:
    image: attxproject/attx-fuseki:fuseki3.4.0
    volumes:
      - ./attx-data/elasticsearch5:/usr/share/elasticsearch/data
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030

  gmapi:
    image: attxproject/gm-api:1.2
    volumes:
      - ./attx-data/gm-api:/app/data
    ports:
      - 4302:4302
    links:
      - fuseki:fuseki
      - es5:es5
      - uprov:uprov
    depends_on:
      - frontend
      - fuseki
      - essiren
      - es5
      - uprov

  mom:
    image: attxproject/attx-activemq:0.1
    ports:
      - 8161:8161
      - 61616:61616
      - 5672:5672
      - 61613:61613
      - 1883:1883
      - 61614:61614


  # demodata:
  #   image: attxproject/demodata:elag2017
  #   ports:
  #     - 80:80
