version: '2'
services:

  mysql:
    image: tenforce/unified-views-mariadb:feat-compact-modular
    volumes:
      - ./uv-data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamroot!

  shared:
    image: tenforce/unified-views-shared:feat-compact-modular

  backend:
    image: tenforce/unified-views-backend:feat-compact-modular
    links:
      - mysql:mysql
    volumes_from:
      - mysql
      - shared

  frontend:
    image: tenforce/unified-views-frontend:feat-compact-modular
    volumes_from:
      - backend
      - shared
    ports:
      - 8080:8080
    depends_on:
      - shared
      - mysql

  uv-dpus:
    image: tenforce/unified-views-add-dpus:feat-compact-modular
    depends_on:
      - mysql
      - backend
      - frontend

  attx-dpus:
    image: attxproject/uv-attx-dpus:elag2017
    depends_on:
      - mysql
      - backend
      - uv-dpus

  wfapi:
    image: attxproject/wf-api:1.0
    ports:
      - 4301:4301
    depends_on:
      - mysql

  essiren:
    image: attxproject/essiren:1.0
    volumes:
      - ./attx-data/essiren:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300

  elasticsearch5:
    image: attxproject/attx-es5:1.0
    volumes:
      - ./attx-data/elasticsearch5:/usr/share/elasticsearch/data
    ports:
      - 9210:9210
      - 9310:9310

  fuseki:
    image: attxproject/attx-fuseki:elag2017
    volumes:
      - ./attx-data/elasticsearch5:/usr/share/elasticsearch/data
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030

  gmapi:
    image: attxproject/gm-api:1.2
    volumes:
      - ./attx-data/gm-api:/app/data
    ports:
      - 4302:4302
    links:
      - fuseki:fuseki
      - elasticsearch5:elasticsearch5
      - wfapi:wfapi
    depends_on:
      - frontend
      - fuseki
      - essiren
      - elasticsearch5
      - wfapi
