#cloud-config
write_files:
  - path: /etc/kontena-agent.env
    permissions: 600
    owner: root
    content: |
      KONTENA_URI="__kontena_master_uri__"
      KONTENA_TOKEN="__grid_token__"
      KONTENA_PEER_INTERFACE=eth1
      KONTENA_VERSION=__kontena_version__
  - path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
    content: |
        [Service]
        Environment='DOCKER_OPTS=--insecure-registry="10.81.0.0/19" --bip="10.255.0.1/16"'
  - path: /etc/systemd/system/locksmithd.service.d/50-reboot-window.conf
    content: |
        [Service]
        Environment='REBOOT_WINDOW_START="Thu 05:00"'
        Environment='REBOOT_WINDOW_LENGTH="1h30m"'

coreos:
  units:
    - name: mkfs-vdb.service
      command: start
      content: |
        [Unit]
        Description=Create ext4 fs on /dev/vdb
        Before=docker.service var-lib-docker.mount
        ConditionPathExists=!/var/lib/docker
        After=dev-vdb.device
        Requires=dev-vdb.device
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/mkfs.ext4 /dev/vdb
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount ephemeral to /var/lib/docker
        Before=docker.service
        Requires=mkfs-vdb.service
        After=mkfs-vdb.service
        [Mount]
        What=/dev/vdb
        Where=/var/lib/docker
        Type=ext4
    - name: 50-docker.network
      mask: true
    - name: 50-docker-veth.network
      mask: true
    - name: zz-default.network
      runtime: false
      content: |
        [Match]
        Name=eth*

        [Network]
        DHCP=yes
        DNS=10.255.0.1
        DNS=193.166.4.24
        DNS=193.166.4.25
        DOMAINS=kontena.local

        [DHCP]
        UseDNS=false
    - name: etcd2.service
      command: start
      enable: true
      content: |
        Description=etcd 2.0
        After=docker.service

        [Service]
        Restart=always
        RestartSec=5
        ExecStart=/usr/bin/docker logs --tail=10 -f kontena-etcd

    - name: 10-weave.network
      runtime: false
      content: |
        [Match]
        Type=bridge
        Name=weave*

        [Network]
    - name: kontena-agent.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=kontena-agent
        After=network-online.target
        After=docker.service
        Description=Kontena Agent
        Documentation=http://www.kontena.io/
        Requires=network-online.target
        Requires=docker.service

        [Service]
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/kontena-agent.env
        ExecStartPre=-/usr/bin/docker stop kontena-agent
        ExecStartPre=-/usr/bin/docker rm kontena-agent
        ExecStartPre=/usr/bin/docker pull kontena/agent:${KONTENA_VERSION}
        ExecStart=/usr/bin/docker run --name kontena-agent \
            -e KONTENA_URI=${KONTENA_URI} \
            -e KONTENA_TOKEN=${KONTENA_TOKEN} \
            -e KONTENA_PEER_INTERFACE=${KONTENA_PEER_INTERFACE} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /etc/kontena-agent.env:/etc/kontena.env \
            --net=host \
            kontena/agent:${KONTENA_VERSION}
